language: php
sudo: false

php:
  - 5.4
  - 7.2

before_script:
  - composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit Test


matrix:
  allow_failures:
    - php: nightly
