language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.2

before_script:
  - composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit Test


matrix:
matrix:
    include:
      - php: 5.3
        dist: precise
    allow_failures:
    - php: nightly
